name: river_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  dio: ^5.1.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  go_router: ^7.0.0
  google_fonts: ^4.0.4
  random_name_generator: ^1.1.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
